services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: helloo
      POSTGRES_PASSWORD: dummy123
      POSTGRES_DB: smarthome_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    working_dir: /app
    ports:
      - "8910:8910"
      - "8911:8911"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
    depends_on:
      - db
    command: sh -c "yarn install && yarn rw prisma generate && yarn rw dev"
    volumes:
      - .:/app
      - web_node_modules:/app/node_modules

volumes:
  db_data:
  web_node_modules: